name: file_converter_app
description: "A new Flutter project."


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  path_provider: ^2.1.5
  image_gallery_saver: ^2.0.3
  image: ^4.5.3
  flutter_image_compress: ^2.4.0
  image_picker: ^1.1.2
  image_cropper: ^9.0.0
  pdf: ^3.11.3
  open_filex: ^4.7.0
  archive: ^4.0.4
  dio: ^5.8.0+1
  flutter_downloader: ^1.12.0
  file_picker: ^9.2.1
  video_compress: ^3.1.4
  media_info: ^0.12.0+2
  iconsax: ^0.0.8
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
